/**
 * 配置页面内联样式定义
 *
 * 基于 ConfigModal 样式，适配全页面布局
 *
 * @module pages/config/configPageStyles
 */

export const styles = {
  container: {
    flex: 1,
    background: '#fff',
    borderRadius: '20px',
    boxShadow: '0 2px 20px rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.03)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  // Header
  header: {
    padding: '28px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #f0eeeb',
    WebkitAppRegion: 'drag',
  },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1.5px solid #d4d0cb',
    background: '#fff',
    color: '#555',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    WebkitAppRegion: 'no-drag',
  },
  backText: {
    fontSize: '13px',
    color: '#555',
  },
  headerTitle: {
    fontSize: '18px',
    fontWeight: 600,
    color: '#2d2d2d',
    margin: 0,
    flex: 1,
    textAlign: 'center',
  },
  headerRight: {
    width: '80px',
  },
  // Content
  content: {
    flex: 1,
    padding: '24px 32px',
    overflowY: 'auto',
    minHeight: 0,
  },
  loading: {
    textAlign: 'center',
    padding: '40px',
    color: '#999',
    fontSize: '14px',
  },
  section: {
    marginBottom: '28px',
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#555',
    marginBottom: '12px',
  },
  pathList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  pathItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 16px',
    borderRadius: '14px',
    border: '1.5px solid #e8e6e3',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    position: 'relative',
  },
  pathItemSelected: {
    background: '#eff6ff',
    borderColor: '#bfdbfe',
  },
  checkbox: {
    width: '20px',
    height: '20px',
    borderRadius: '6px',
    border: '1.5px solid #d4d0cb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s ease',
    background: '#fff',
    flexShrink: 0,
    marginRight: '12px',
  },
  checkboxChecked: {
    background: '#2563eb',
    borderColor: '#2563eb',
  },
  pathIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    marginRight: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    flexShrink: 0,
    background: '#f5f3f0',
    color: '#888',
  },
  pathInfo: {
    flex: 1,
    minWidth: 0,
  },
  pathName: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#2d2d2d',
  },
  pathMeta: {
    fontSize: '11px',
    color: '#999',
    marginTop: '4px',
  },
  deleteBtn: {
    padding: '6px 12px',
    borderRadius: '8px',
    border: 'none',
    background: 'transparent',
    color: '#c45a5a',
    fontSize: '12px',
    cursor: 'pointer',
    opacity: 0,
    transition: 'all 0.15s ease',
  },
  addBtnRow: {
    marginTop: '12px',
  },
  addPathBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px',
    borderRadius: '10px',
    border: '1.5px dashed #d4d0cb',
    background: 'transparent',
    color: '#888',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    width: '100%',
  },
  toolList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  toolItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 12px',
    cursor: 'pointer',
    borderRadius: '8px',
    transition: 'background 0.15s',
  },
  toolItemUnchecked: {
    opacity: 0.7,
  },
  toolCheckbox: {
    width: '16px',
    height: '16px',
    borderRadius: '4px',
    border: '1.5px solid #d4d0cb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: '10px',
    color: '#fff',
  },
  toolCheckboxChecked: {
    background: '#2563eb',
    borderColor: '#2563eb',
  },
  toolInfo: {
    flex: 1,
  },
  toolName: {
    fontSize: '13px',
    color: '#2d2d2d',
  },
  toolPath: {
    fontSize: '11px',
    color: '#999',
    marginTop: '2px',
  },
  empty: {
    textAlign: 'center',
    padding: '20px',
    color: '#999',
    fontSize: '13px',
  },
  error: {
    color: '#c45a5a',
    fontSize: '13px',
    textAlign: 'center',
    padding: '10px',
    background: '#fdf2f2',
    borderRadius: '8px',
    marginTop: '10px',
  },
  // Footer
  footer: {
    padding: '16px 32px',
    borderTop: '1px solid #f0eeeb',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  btn: {
    padding: '10px 24px',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid #d4d0cb',
    background: '#fff',
    color: '#555',
    transition: 'all 0.15s',
  },
  btnPrimary: {
    background: '#2563eb',
    color: '#fff',
    borderColor: '#2563eb',
  },
}
