/** Visible Plan states and request isolation. @module tests/PlanManagementPage */
import React from 'react'
import {it,expect,vi,afterEach} from 'vitest'
import {render,screen,fireEvent,cleanup,waitFor,within,act} from '@testing-library/react'
import PlanCard from '../../src/pages/plan/components/PlanCard'
import PlanManagementPage from '../../src/pages/PlanManagementPage'
afterEach(()=>{cleanup();delete window.electronAPI;delete window.__planTestVersion})
const period=(start='2026-08-20',end='2026-09-20',price=20)=>({id:start,start,end,price})
const fixture=(extra={})=>{const cycle=period();return{planId:'claude',name:'Claude Code',plan:{price:20,billingDay:20,autoRenew:false,version:1,stopped:false,cycles:[cycle]},cycle,metadata:{type:'Pro',suggestedPrice:20},today:'2026-09-16',usage:{total:751,models:[{name:'Claude Opus 5',cost:562},{name:'Claude Fable 5.1',cost:183},{name:'Claude Sonnet 5',cost:6}]},onSave:vi.fn(async()=>({success:true})),onNavigate:vi.fn(),onAction:vi.fn(),...extra}}
const card=extra=>{const f=fixture(extra);render(<div className="plan-page"><PlanCard {...f}/></div>);return f}
it('TC-001 normal hierarchy contains only original header and three value rows',()=>{card();expect(screen.getByText('38×')).toBeVisible();expect(screen.getByText('省了 $731')).toBeVisible();for(const text of ['订阅费','等价 API','周期','Claude Opus 5'])expect(screen.getByText(text)).toBeVisible();expect(screen.queryByText('会员额度')).toBeNull()})
it('TC-004 six models plus aggregate other use unrounded amount ordering',()=>{card({usage:{total:360,models:Array.from({length:8},(_,i)=>({name:'Claude model '+i,cost:[100,80,60,40,30,20,20,10][i]}))}});expect(screen.getByText('其他 2 个')).toBeVisible();expect(screen.getAllByText('$30')).toHaveLength(2);expect(screen.getAllByTestId('plan-model-row')).toHaveLength(7)})
it('TC-005 configured zero usage is blue zero with original empty phrase',()=>{card({usage:{total:0,models:[]}});expect(screen.getByText('0.0×')).toBeVisible();expect(screen.getByText('本周期还没有用量')).toBeVisible();expect(screen.queryByText(/还差/)).toBeNull()})
it('TC-007 metadata billing hint is draft only, never creates first cycle',()=>{const p={version:0,cycles:[],stopped:false};card({plan:p,cycle:null,usage:null,metadata:{type:'prolite',suggestedBillingDay:20}});expect(screen.getByText('填订阅费后计算')).toBeVisible();expect(screen.queryByText('周期')).toBeNull();expect(screen.queryByText('正在统计…')).toBeNull()})
it('TC-010 positive usage below price is red with shortfall',()=>{card({cycle:period(undefined,undefined,100),usage:{total:62,models:[]}});expect(screen.getByText('0.6×')).toHaveClass('plan-bad');expect(screen.getByText('还差 $38 回本')).toBeVisible()})
it('TC-013 configured loading preserves in-card skeleton and hierarchy',()=>{card({loading:true,usage:null});expect(screen.getByText('正在统计…')).toBeVisible();expect(screen.getByTestId('plan-card')).toHaveClass('plan-sk');expect(screen.queryByText('本周期还没有用量')).toBeNull()})
it('TC-014 original subscription value opens anchored readonly type and fields',()=>{card();fireEvent.click(screen.getByRole('button',{name:'Claude Code 订阅设置'}));expect(screen.getByText('Claude Code 订阅')).toBeVisible();expect(screen.getByLabelText('订阅费')).toHaveValue('20');expect(screen.getByLabelText('账单日')).toHaveValue('20');expect(screen.getByText('Pro · 本机读到')).toBeVisible()})
it('TC-020 expired no autoRenew shows original confirmation and two actions',()=>{card({today:'2026-09-23'});expect(screen.getByText('已到期 · 待确认')).toBeVisible();expect(screen.getByText('这期续了吗？')).toBeVisible();expect(screen.getByRole('button',{name:'续了一期'})).toBeVisible();expect(screen.getByRole('button',{name:'不续了'})).toBeVisible();expect(screen.queryByText('省了 $731')).toBeNull()})
it('TC-021 stop action shows original paused result and restart',()=>{const f=fixture();card({plan:{...f.plan,stopped:true},today:'2026-10-05'});expect(screen.getByText('已停 · 最后一期结果')).toBeVisible();expect(screen.getByRole('button',{name:'重新开始，从今天起算'})).toBeVisible();expect(screen.getByTestId('plan-card')).toHaveClass('plan-paused')})
it('TC-023 successful commit triggers only original success Toast',async()=>{
 const f=fixture();window.electronAPI={readPlan:vi.fn(async({planId})=>({success:true,data:{plan:planId==='claude'?f.plan:{cycles:[],version:0},metadata:f.metadata,today:f.today}})),queryPlan:vi.fn(async()=>({success:true,data:{...f.usage,version:window.__planTestVersion||1,cycleId:f.cycle.id}})),savePlan:vi.fn(async()=>{window.__planTestVersion=2;return {success:true,data:{plan:{...f.plan,version:2,price:100,cycles:[{...f.cycle,price:100}]},metadata:f.metadata,today:f.today}}})};render(<PlanManagementPage/>);await screen.findByText('38×');fireEvent.click(screen.getByRole('button',{name:'Claude Code 订阅设置'}));fireEvent.change(screen.getByLabelText('订阅费'),{target:{value:'100'}});fireEvent.keyDown(screen.getByLabelText('订阅费'),{key:'Enter'});await screen.findByText('Claude Code 订阅已更新');expect(window.electronAPI.savePlan).toHaveBeenCalledTimes(1)
})
it('TC-024 page renders exactly two cards in source order',async()=>{const f=fixture();window.electronAPI={readPlan:vi.fn(async()=>({success:true,data:{plan:{cycles:[],version:0},metadata:f.metadata,today:f.today}}))};render(<PlanManagementPage/>);await waitFor(()=>expect(window.electronAPI.readPlan).toHaveBeenCalledTimes(2));expect(screen.getAllByTestId('plan-card')).toHaveLength(2);expect(screen.getAllByTestId('plan-card')[0]).toHaveAttribute('data-plan-id','claude')})
it('TC-025 subscription/API/model amounts occupy original aligned slots',()=>{card();expect(screen.getByTestId('plan-values')).toHaveClass('plan-kv');expect(screen.getAllByTestId('plan-model-row')[0].lastElementChild).toHaveClass('plan-v')})
it('TC-026 normal viewport keeps original compact two-card layout',()=>{card();expect(screen.getByTestId('plan-card-number-region')).toHaveClass('plan-top');expect(screen.getAllByTestId('plan-model-row')).toHaveLength(3)})
it('TC-027 header carries lifecycle tag but no subscription setting entry',()=>{card({today:'2026-09-18'});const h=screen.getByTestId('plan-card-header');expect(within(h).getByText('快到期')).toBeVisible();expect(within(h).queryByRole('button',{name:'Claude Code 订阅设置'})).toBeNull()})
it('TC-028 remaining1 is today expiry, remaining4 has no warning',()=>{card({today:'2026-09-19'});expect(screen.getByText('今天到期')).toBeVisible();expect(screen.getByText('快到期')).toBeVisible();cleanup();card({today:'2026-09-16'});expect(screen.queryByText('快到期')).toBeNull();expect(screen.getByText('还剩 4 天')).toBeVisible()})
it('TC-029 earliest left and current right navigation are disabled',()=>{card();expect(screen.getByRole('button',{name:'上一周期'})).toBeDisabled();expect(screen.getByRole('button',{name:'下一周期'})).toBeDisabled()})
it('TC-030 historical price uses ended snapshot with full progress',()=>{const old=period('2026-07-20','2026-08-20');const f=fixture();card({plan:{...f.plan,price:100,cycles:[old,f.cycle]},cycle:old,usage:{total:412,models:[]}});expect(screen.getByText('21×')).toBeVisible();expect(screen.getByText('已结束')).toBeVisible();expect(screen.getByText('已结束 · 31 天')).toBeVisible();expect(screen.getByRole('button',{name:'下一周期'})).not.toBeDisabled()})
it('TC-031 card hover leaves its semantic DOM unchanged with no whole-card tooltip',()=>{card();const c=screen.getByTestId('plan-card');const before=c.innerHTML;fireEvent.mouseEnter(c);expect(c.innerHTML).toBe(before);expect(c).not.toHaveAttribute('title')})
it('TC-032 long model names keep original single row and full-name tooltip',()=>{const name='Claude very long canonical model name which cannot fit in 120px';card({usage:{total:2,models:[{name,cost:2}]}});expect(screen.getByText(name)).toHaveAttribute('title',name)})
for(const [id,width,height] of [['TC-043',800,600],['TC-081',720,500]])it(id+' dense data keeps seven rows per card for native screenshot verification',()=>{const f=fixture({usage:{total:360,models:Array.from({length:8},(_,i)=>({name:'Claude model '+i,cost:100-i*10}))}});render(<div className="plan-page" style={{width,height}}><div className="plan-scroll" data-testid="plan-content-scroll-container"><PlanCard {...f}/><PlanCard {...f} planId="codex" name="Codex"/></div></div>);expect(screen.getAllByTestId('plan-model-row')).toHaveLength(14);expect(screen.getAllByTestId('plan-model-list-last-row')).toHaveLength(2);expect(screen.getByTestId('plan-content-scroll-container')).toHaveClass('plan-scroll')})
it('TC-063 unset Claude does not query, configured Codex queries independently',async()=>{const f=fixture();window.electronAPI={readPlan:vi.fn(async({planId})=>({success:true,data:{plan:planId==='claude'?{cycles:[],version:0}:f.plan,metadata:f.metadata,today:f.today}})),queryPlan:vi.fn(async({planId,cycleId})=>({success:true,data:{total:751,models:[],version:1,cycleId}}))};render(<PlanManagementPage/>);await screen.findByText('38×');expect(window.electronAPI.queryPlan).toHaveBeenCalledTimes(1);expect(window.electronAPI.queryPlan.mock.calls[0][0].planId).toBe('codex');expect(screen.getAllByText('填订阅费后计算')).toHaveLength(1)})
it('TC-064 late old query cannot replace newer selected cycle and amount',async()=>{
 const f=fixture();let oldResolve;const next=period('2026-09-17','2026-10-17');const nextPlan={...f.plan,version:2,stopped:false,billingDay:17,cycles:[f.cycle,next]};window.electronAPI={readPlan:vi.fn(async()=>({success:true,data:{plan:{...f.plan,stopped:true},metadata:f.metadata,today:'2026-09-17'}})),queryPlan:vi.fn(({planId,cycleId})=>cycleId===next.id?Promise.resolve({success:true,data:{total:2,models:[],version:2,cycleId}}):new Promise(r=>{if(planId==='claude')oldResolve=r})),actPlan:vi.fn(async()=>({success:true,data:{plan:nextPlan,metadata:f.metadata,today:'2026-09-17'}}))};render(<PlanManagementPage/>);await waitFor(()=>expect(oldResolve).toBeTypeOf('function'));const cl=screen.getAllByTestId('plan-card')[0];fireEvent.click(within(cl).getByRole('button',{name:'重新开始，从今天起算'}));await within(cl).findByText('0.1×');await act(async()=>oldResolve({success:true,data:{total:100,models:[],version:1,cycleId:f.cycle.id}}));expect(within(cl).getByText('0.1×')).toBeVisible();expect(within(cl).queryByText('5.0×')).toBeNull()
})
it('TC-066 current price warning appears only for ongoing draft',()=>{card();fireEvent.click(screen.getByRole('button',{name:'Claude Code 订阅设置'}));fireEvent.change(screen.getByLabelText('订阅费'),{target:{value:'100'}});expect(screen.getByText(/改价从本周期起按 \$100 算/)).toBeVisible();cleanup();card({today:'2026-09-23'});fireEvent.click(screen.getByRole('button',{name:'Claude Code 订阅设置'}));fireEvent.change(screen.getByLabelText('订阅费'),{target:{value:'100'}});expect(screen.queryByText(/改价从本周期起/)).toBeNull()})
it('TC-067 expired and stopped lifecycle subtitles override shortfall',()=>{card({today:'2026-09-23',usage:{total:12,models:[]}});expect(screen.getByText('这期续了吗？')).toBeVisible();expect(screen.queryByText(/还差/)).toBeNull();cleanup();const f=fixture();card({plan:{...f.plan,stopped:true},usage:{total:12,models:[]}});expect(screen.getByText('已停 · 最后一期结果')).toBeVisible();expect(screen.queryByText(/还差/)).toBeNull()})
it('TC-068 expiry warning and red shortfall coexist',()=>{card({today:'2026-09-18',usage:{total:12,models:[]}});expect(screen.getByText('快到期')).toBeVisible();expect(screen.getByText('0.6×')).toHaveClass('plan-bad');expect(screen.getByText('还剩 2 天')).toHaveClass('plan-warn')})
it('TC-079 new cycle first day does not inherit old usage or warning',()=>{const cycle=period('2026-09-20','2026-10-20');card({cycle,plan:{...fixture().plan,cycles:[cycle],autoRenew:true},today:'2026-09-20',usage:{total:0,models:[]}});expect(screen.getByText('0.0×')).not.toHaveClass('plan-bad');expect(screen.getByText('还剩 30 天')).toBeVisible();expect(screen.queryByText(/还差/)).toBeNull()})
it('TC-057 all unpriced retains dates/models but no profit or fake zero',()=>{card({usage:{total:null,models:[{name:'claude-new-9',cost:null}]}});expect(screen.getAllByText('—')).toHaveLength(3);expect(screen.getByText('还剩 4 天')).toBeVisible();expect(screen.queryByText(/还差|省了|填订阅费|正在统计/)).toBeNull()})
it('TC-062 read failure retains cycle and subscription without fake model results',()=>{card({error:'PLAN_QUERY_FAILED',usage:null});expect(screen.getAllByText('—')).toHaveLength(2);expect(screen.getByText('$20')).toBeVisible();expect(screen.getByText('还剩 4 天')).toBeVisible();expect(screen.queryByText('本周期还没有用量')).toBeNull();expect(screen.queryAllByTestId('plan-model-row')).toHaveLength(0)})

it('TC-007/TC-016 complete first-time prefill stays draft until Enter and then commits once',async()=>{
 const onSave=vi.fn(async()=>({success:true}));card({plan:{version:0,cycles:[],stopped:false},cycle:null,usage:null,metadata:{type:'plus',suggestedPrice:20,suggestedBillingDay:20},onSave});
 fireEvent.click(screen.getByRole('button',{name:'Claude Code 订阅设置'}));
 expect(screen.getByLabelText('订阅费')).toHaveValue('20');expect(screen.getByLabelText('账单日')).toHaveValue('20');expect(onSave).toHaveBeenCalledTimes(0);
 fireEvent.keyDown(screen.getByLabelText('订阅费'),{key:'Enter'});await act(async()=>{});
 expect(onSave).toHaveBeenCalledTimes(1);expect(onSave.mock.calls[0][0]).toEqual({price:20,billingDay:20,autoRenew:false});
 fireEvent.keyDown(screen.getByLabelText('订阅费'),{key:'Enter'});fireEvent.blur(screen.getByLabelText('订阅费'),{relatedTarget:screen.getByLabelText('账单日')});await act(async()=>{});expect(onSave).toHaveBeenCalledTimes(1);
})

for (const browsingHistory of [false,true]) it('TC-073 shared revision after autoRenew '+(browsingHistory?'preserves explicitly browsed history':'follows the newly current cycle'),async()=>{
 const older=period('2026-07-20','2026-08-20');const old=period();const next=period('2026-09-20','2026-10-20');let afterBoundary=false,sharedChanged;
 const beforePlan={price:20,billingDay:20,autoRenew:true,stopped:false,version:1,cycles:[older,old]};const afterPlan={...beforePlan,version:2,cycles:[older,old,next]};
 window.electronAPI={onUsageStatisticsChanged:fn=>{sharedChanged=fn;return()=>{}},readPlan:vi.fn(async({planId})=>({success:true,data:{plan:planId==='claude'?(afterBoundary?afterPlan:beforePlan):{cycles:[],version:0,stopped:false},metadata:{type:'Pro'},today:afterBoundary?'2026-09-20':'2026-09-19'}})),queryPlan:vi.fn(async({cycleId})=>({success:true,data:{version:afterBoundary?2:1,cycleId,total:cycleId===next.id?0:cycleId===older.id?412:751,models:[]}}))};
 render(<PlanManagementPage/>);const cl=screen.getAllByTestId('plan-card')[0];await within(cl).findByText('38×');
 if(browsingHistory){fireEvent.click(within(cl).getByRole('button',{name:'上一周期'}));await within(cl).findByText('21×')}
 const queryCount=window.electronAPI.queryPlan.mock.calls.length;afterBoundary=true;act(()=>sharedChanged({revision:2}));await waitFor(()=>expect(window.electronAPI.queryPlan.mock.calls.length).toBeGreaterThan(queryCount));
 if(browsingHistory){await within(cl).findByText('21×');expect(within(cl).getByText('07.20 – 08.20')).toBeVisible()}
 else{await within(cl).findByText('0.0×');expect(within(cl).getByText('09.20 – 10.20')).toBeVisible();expect(within(cl).queryByText('已结束')).toBeNull()}
})
